# Site settings
title: Dunn
email: twdunn@fas.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Timothy Dunn's personal website. Neuroscience and biological data analysis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spoonsso.github.io" # the base hostname & protocol for your site
github_username:  spoonsso
favicon: "/images/favicon.ico"

# Build settings
markdown: kramdown
